In [12]:
import numpy as np
import pandas as pd

# Data Visualisation
import matplotlib.pyplot as plt 
import seaborn as sns

In [13]:
df = pd.DataFrame(pd.read_csv(r"C:\Users\G NIHITHA\Desktop\ML LAB\insurance.csv"))
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [14]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [15]:
X = df[['bmi']]
y = df['charges']

In [16]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
X= mm_scaler.fit_transform(X)
mm_scaler.transform(X)

array([[-0.42073643],
       [-0.41648776],
       [-0.41704508],
       ...,
       [-0.41425848],
       [-0.4222564 ],
       [-0.41988959]])

In [17]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
y= mm_scaler.fit_transform(y.values.reshape(-1,1))
mm_scaler.transform(y.reshape(-1,1))

array([[-0.0179034 ],
       [-0.01790727],
       [-0.01790657],
       ...,
       [-0.01790729],
       [-0.01790719],
       [-0.01790028]])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.3, test_size = 0.7, random_state = 100)

In [19]:
from sklearn.linear_model import LinearRegression

#lm2 = LinearRegression()
lm2 = Lasso()
lm2.fit(X_train, y_train)
print(lm2.intercept_)
print(lm2.coef_)

[0.11132776]
[[0.16904131]]


In [20]:
X_test


array([[0.496099  ],
       [0.31046543],
       [0.31436642],
       [0.41700296],
       [0.24791499],
       [0.31692225],
       [0.48305085],
       [0.26324993],
       [0.25127791],
       [0.6031746 ],
       [0.84907183],
       [0.43771859],
       [0.4677159 ],
       [0.39359699],
       [0.38310465],
       [0.5472155 ],
       [0.41108421],
       [0.42884046],
       [0.39117568],
       [0.89050309],
       [0.60048426],
       [0.40731773],
       [0.145682  ],
       [0.23258004],
       [0.55716976],
       [0.59550713],
       [0.52394404],
       [0.54950229],
       [0.23513586],
       [0.3755717 ],
       [0.8283562 ],
       [0.34503632],
       [0.55972559],
       [0.42426688],
       [0.37503363],
       [0.15334948],
       [0.61528114],
       [0.49071832],
       [0.25558246],
       [0.3755717 ],
       [0.26472962],
       [0.68240517],
       [0.47619048],
       [0.55609362],
       [0.24535916],
       [0.34893732],
       [0.31638418],
       [0.442

In [21]:
New_1 = 0.2933572
print ('Predicted Value: \n', lm2.predict([[New_1]]))

Predicted Value: 
 [[0.16091725]]


In [22]:
predict=lm2.predict(X_train)
predict

array([[0.18331926],
       [0.14157056],
       [0.22133877],
       [0.17472394],
       [0.2083321 ],
       [0.14652765],
       [0.1441628 ],
       [0.14516331],
       [0.15021136],
       [0.18732131],
       [0.24234956],
       [0.1324295 ],
       [0.22183903],
       [0.18391047],
       [0.17915803],
       [0.19109598],
       [0.14780103],
       [0.1528036 ],
       [0.17699783],
       [0.19687167],
       [0.20746802],
       [0.20853675],
       [0.14502688],
       [0.19232388],
       [0.21833723],
       [0.2303434 ],
       [0.20746802],
       [0.18245518],
       [0.15107544],
       [0.20076003],
       [0.17397355],
       [0.13941036],
       [0.17927173],
       [0.19132337],
       [0.16531002],
       [0.14834676],
       [0.21674551],
       [0.16446867],
       [0.18607067],
       [0.21933775],
       [0.16662887],
       [0.1528036 ],
       [0.17699783],
       [0.17431464],
       [0.17426916],
       [0.18518385],
       [0.17440559],
       [0.173

In [29]:
bias=y_train-predict
bias.mean()

-5.814135540430994e-18

In [24]:
lm2.score(X_train, y_train)

0.022425381128508337

In [25]:
pred=lm2.predict(X_test)
pred

array([[0.19518899],
       [0.16380925],
       [0.16446867],
       [0.18181849],
       [0.15323564],
       [0.16490071],
       [0.19298331],
       [0.15582788],
       [0.15380411],
       [0.21328919],
       [0.25485598],
       [0.18532029],
       [0.19039107],
       [0.17786191],
       [0.17608828],
       [0.20382979],
       [0.18081798],
       [0.18381952],
       [0.17745261],
       [0.26185957],
       [0.21283441],
       [0.18018129],
       [0.13595404],
       [0.1506434 ],
       [0.20551247],
       [0.21199307],
       [0.19989595],
       [0.20421635],
       [0.15107544],
       [0.17481489],
       [0.25135418],
       [0.16965315],
       [0.20594451],
       [0.18304639],
       [0.17472394],
       [0.13725016],
       [0.21533569],
       [0.19427943],
       [0.15453176],
       [0.17481489],
       [0.156078  ],
       [0.22668243],
       [0.19182362],
       [0.20533056],
       [0.1528036 ],
       [0.17031258],
       [0.16480976],
       [0.186

In [30]:
Variance = y_test-pred
print(Variance.mean())

0.02244777799767815


In [27]:
lm2.score(X_test,y_test)

0.02936579438636311