In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler(feature_range=(0,1))

In [4]:
x=df.drop("y",axis=1)
y=df["y"]

KeyError: "['y'] not found in axis"

In [ ]:
x=minmax.fit(x).transform(x)

In [5]:
x

NameError: name 'x' is not defined

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.6, test_size = 0.4, random_state = 100)

<h4>Logistic<h4>

In [12]:
from sklearn.linear_model import LogisticRegression 

In [14]:
logmodel=LogisticRegression()
logmodel.fit(X_train,y_train) 

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
logmodel.coef_

array([[ 3.84893650e-01, -8.42338196e-01,  1.24940627e+00,
         8.33297687e-01,  8.80737533e+00, -8.34826476e-01,
        -7.28176649e-01, -1.59087206e+00, -8.00170975e-01,
         5.04370322e-01,  4.36001501e-02,  4.16644598e-02,
        -3.90001132e-01,  2.34130418e-01,  1.52382935e-02,
        -2.25327565e-01, -3.50612367e-01,  1.82787782e-01,
        -2.78993993e-01,  1.77892071e-01,  1.80458983e-01,
        -1.75236588e-01, -3.94214540e-02, -1.54504860e-01,
        -5.63831792e-02,  1.90457468e-01, -3.35377505e-01,
         7.10429725e-02, -1.79397569e-01, -1.84995453e-01,
         1.25490364e-01, -1.72632889e-01, -1.96530012e-01,
        -1.14774824e-01, -2.54388077e-01,  3.88621381e-02,
        -4.08025039e-01, -2.00685575e-01, -9.62821955e-02,
         8.52006879e-02,  8.48750407e-03,  3.09811873e-01,
         1.64745817e+00, -7.75409697e-01, -4.40138281e-01,
        -7.39261850e-01, -1.68343540e-01, -2.06201547e-01,
        -1.42477135e-02, -3.31288548e-02, -9.66109226e-0

In [26]:
logmodel.intercept_

array([-0.3691629])

In [15]:
prediction=logmodel.predict(X_train)

In [22]:
prediction1=logmodel.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y_train,prediction) 

0.9141666666666667

In [23]:
accuracy_score(y_test,prediction1)

0.9031855090568395

In [19]:
from sklearn.metrics import confusion_matrix

In [21]:
confusion_matrix(y_train,prediction) 

array([[2109,   32],
       [ 174,   85]], dtype=int64)

<h4>Naive bayes<h4>

In [30]:
from sklearn.naive_bayes import GaussianNB

In [31]:
model=GaussianNB()

In [32]:
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [33]:
navi_predict=model.predict(X_train)

In [34]:
navi_predict

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
predi=logmodel.predict(X_test)

In [42]:
accuracy_score(y_test,predi)

0.9031855090568395

In [43]:
accuracy_score(y_train,navi_predict)

0.79875